from PyRM.configs import ConfigImprov
from PyRM.configs import ConfigNoteBase
from PyRM.configs import ConfigPhrase
from PyRM.configs import ConfigSpace
from PyRM.configs import ConfigTempo
from PyRM.configs import ConfigVolume
from PyRM.configs import Drum808
from PyRM.configs import DrumBlues
from PyRM.configs import DrumBully
from PyRM.configs import DrumEzxJazz
from PyRM.configs import DrumHell
from PyRM.configs import DrumKrimh
from PyRM.configs import DrumVintage1963
from PyRM.configs import MapDrumFast
from PyRM.configs import MapDrumSlow
from PyRM.configs import MapPianoComp
from PyRM.configs import MapPianoOrnament
from PyRM.configs import MapPianoPad
from PyRM.configs import NoteCategory
from PyRM.configs import PIanoPad
from PyRM.configs import PianoComp
from PyRM.configs import PianoLongNotes
from PyRM.configs import PianoOrnament
from PyRM.configs import SynthPad
from PyRM.configs import Vibes
