from aenum import Enum
from aenum import extend_enum

class NoteCategory(Enum):
    CRASH = "Cymbal Crashes"
    HAT = "Hi-Hat"
    KICK = "Kick"
    RIDE = "Ride cymbal"
    SNARE = "Snare"
    TOM = "Toms"
    FX = "FX"
    
    # piano sections
    LOW = "Low"
    MIDDLE = "Middle"
    HIGH = "High"
    
    ACOUSTIC = "ACOUSTIC"
    AEOLIAN_DOMINANT = "AEOLIAN_DOMINANT"
    ALGERIAN = "ALGERIAN"
    ALGERIAN_2 = "ALGERIAN_2"
    AUGMENTED = "AUGMENTED"
    BALINESE = "BALINESE"
    BYZANTINE = "BYZANTINE"
    CHINESE = "CHINESE"
    CHROMATIC = "CHROMATIC"
    DIMINISHED = "DIMINISHED"
    DOMINANT_DIMINISHED = "DOMINANT_DIMINISHED"
    EGYPTIAN = "EGYPTIAN"
    EIGHT_TONE_SPANISH = "EIGHT_TONE_SPANISH"
    HARMONIC_MINOR = "HARMONIC_MINOR"
    HAWAIIAN = "HAWAIIAN"
    HIRAJŌSHI = "HIRAJŌSHI"
    HUNGARIAN = "HUNGARIAN"
    HUNGARIAN_MAJOR = "HUNGARIAN_MAJOR"
    IBERIAN = "IBERIAN"
    IWATO = "IWATO"
    JAPANESE = "JAPANESE"
    NEOPOLITAN_MAJOR = "NEOPOLITAN_MAJOR"
    NEOPOLITAN_MINOR = "NEOPOLITAN_MINOR"
    ORIENTAL = "ORIENTAL"
    PHRYGIAN_DOMINANT = "PHRYGIAN_DOMINANT"
    PROMETHEUS = "PROMETHEUS"
    ROMANIAN_MINOR = "ROMANIAN_MINOR"
    SUPER_LOCRIAN = "SUPER_LOCRIAN"
    WHOLE_TONE = "WHOLE_TONE"
    YO = "YO"
    
    def __str__(self):
        return self.name
